#ifndef eGUIShapeGeometry_H
#define eGUIShapeGeometry_H

enum eGUIShapeGeometry
{
	GUI_SHAPE_GEOMETRY_1_POINT_1_X_1D_SIZE,
	GUI_SHAPE_GEOMETRY_1_POINT_1_X_2D_SIZE,
	GUI_SHAPE_GEOMETRY_2_POINTS,
	GUI_SHAPE_GEOMETRY_3_POINTS,
	GUI_SHAPE_GEOMETRY_N_POINTS
};

#endif