#ifndef eRWSection_H
#define eRWSection_H

#include "bxgi.h"
#include "Type/Types.h"

enum bxgi::eRWSection : uint32
{
	RW_SECTION_UNKNOWN				= 0xFFFFFFFF,
	RW_SECTION_STRUCT				= 0x01,
	RW_SECTION_STRING				= 0x02,
	RW_SECTION_EXTENSION			= 0x03,
	RW_SECTION_TEXTURE				= 0x06,
	RW_SECTION_MATERIAL				= 0x07,
	RW_SECTION_MATERIAL_LIST		= 0x08,
	RW_SECTION_FRAME_LIST			= 0x0e,
	RW_SECTION_GEOMETRY				= 0x0f,
	RW_SECTION_CLUMP				= 0x10,
	RW_SECTION_LIGHT				= 0x12,
	RW_SECTION_ATOMIC				= 0x14,
	RW_SECTION_TEXTURE_NATIVE		= 0x15,
	RW_SECTION_TEXTURE_DICTIONARY	= 0x16,
	RW_SECTION_GEOMETRY_LIST		= 0x1a,
	RW_SECTION_BIN_MESH_PLG			= 0x50E,
	//RW_SECTION_MORPH_PLG			= 0x105, // todo
	//RW_SECTION_MATERIAL_EFFECTS_PLG	= 0x120, // todo
	RW_SECTION_2D_EFFECT			= 0x0253F2F8,
	RW_SECTION_EXTRA_VERT_COLOUR	= 0x0253F2F9,
	RW_SECTION_FRAME				= 0x0253F2FE
};

#endif