#pragma once

#include "nsbxgi.h"
#include "Type/Types.h"

enum bxgi::E2DFXType
{
	_2DFX_UNKNOWN,

	// IDE - GTA III era & some GTA IV
	_2DFX_LIGHT, // DFF too
	_2DFX_PARTICLE, // DFF too
	_2DFX_UNKNOWN_1,
	_2DFX_PED,
	_2DFX_SUN_REFLECTION,

	// IDE - GTA IV
	_2DFX_EXPLOSION,
	_2DFX_ESCALATOR, // DFF too
	_2DFX_PROC_OBJECT,
	_2DFX_WORLD_POINT,
	_2DFX_LADDER,
	_2DFX_AUDIO,
	_2DFX_SPAWN_POINT,
	_2DFX_LIGHT_SHAFT,
	_2DFX_SCROLL_BAR,
	_2DFX_SWAYABLE_ATTR,
	_2DFX_BOUYANCY_ATTR,
	_2DFX_WALK_DONT_WALK_ATTR,

	// DFF
	_2DFX_COVER_POINT,
	_2DFX_ENTER_EXIT,
	_2DFX_PED_ATTRACTOR,
	_2DFX_SLOT_MACHINE_WHEEL,
	_2DFX_STREET_SIGN,
	_2DFX_SUN_GLARE
};