#ifndef WindowControlIds_H
#define WindowControlIds_H

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101

#define IDR_MAINFRAME                   128

#define IDR_MENU2                       102

#define IDD_DIALOG1						100
#define IDD_TEXTINPUTDIALOG				200
#define IDD_CONVERTDIALOG				300
#define IDD_CONVERTVIADIALOG			350
#define IDD_EXPORTVIADIALOG				400
#define IDD_TEXTAREADIALOG				500
#define IDD_SORTOPTIONSDIALOG			600
#define IDD_REMOVEVIADIALOG				700
#define IDD_IMPORTVIADIALOG				800
#define IDD_STATSDIALOG					900
#define IDD_LISTVIEWDIALOG				950
#define IDD_ORPHANENTRIESDIALOG			960
#define IDD_SETTINGSDIALOG				970
#define IDD_CONFIRMDIALOG				980
#define IDD_DUMPDIALOG					990
#define IDD_SESSIONMANAGERDIALOG		991
#define IDD_SPLITVIADIALOG				992
#define IDD_DRAGDROPDIALOG				993
#define IDD_DUMPRESULTSDIALOG			994
#define IDD_CREDITSDIALOG				995
#define IDD_RENAMERDIALOG				996
#define IDD_DFFCONVERSIONDIALOG			997
#define IDD_DUPLICATEENTRIESDIALOG		998
#define IDD_BUILDTXDDIALOG				999
#define IDD_IMGVERSIONSETTINGSDIALOG	951
#define IDD_TXDORGANIZERDIALOG			952
#define IDD_DATPATHSMOVERDIALOG			953
#define IDD_MAPMOVERANDIDSHIFTERDIALOG	954
#define IDD_DATMODELLISTDIALOG			955
#define IDD_OVERWRITEENTRYDIALOG		956
#define IDD_3BUTTONDIALOG				957

#endif