#ifndef eGUIControl_H
#define eGUIControl_H

enum eGUIControl
{
	GUI_CONTROL_UNKNOWN,

	GUI_CONTROL_BUTTON,
	GUI_CONTROL_CHECK,
	GUI_CONTROL_DROP,
	GUI_CONTROL_IMAGE,
	GUI_CONTROL_GRID,
	GUI_CONTROL_MENU,
	GUI_CONTROL_PROGRESS,
	GUI_CONTROL_RADIO,
	GUI_CONTROL_SCROLL,
	GUI_CONTROL_TAB_BAR,
	GUI_CONTROL_TEXT,
	GUI_CONTROL_TEXT_BOX
};

#endif