#ifndef eGUIControl_H
#define eGUIControl_H

enum eGUIControl
{
	GUI_CONTROL_UNKNOWN,

	GUI_CONTROL_BUTTON,
	GUI_CONTROL_CHECK,
	GUI_CONTROL_DROP,
	GUI_CONTROL_EDIT,
	GUI_CONTROL_IMAGE,
	GUI_CONTROL_LIST,
	GUI_CONTROL_MENU,
	GUI_CONTROL_PROGRESS,
	GUI_CONTROL_RADIO,
	GUI_CONTROL_SCROLL,
	GUI_CONTROL_TAB,
	GUI_CONTROL_TEXT
};

#endif