#pragma once

/* This file is automatically modified upon build */

#define IMGF_MAJOR_BUILD_VERSION			2
#define IMGF_MAJOR_BUILD_VERSION_STRING		std::string("2")
#define IMGF_MAJOR_BUILD_VERSION_CSTRING	"2"

#define IMGF_MINOR_BUILD_VERSION			14835
#define IMGF_MINOR_BUILD_VERSION_STRING		std::string("14835")
#define IMGF_MINOR_BUILD_VERSION_CSTRING	"14835"

#define IMGF_BUILD_VERSION_STRING			IMGF_MINOR_BUILD_VERSION_STRING