#pragma once

/* This file is automatically modified upon build */

#define IMGF_MAJOR_BUILD_VERSION			2
#define IMGF_MAJOR_BUILD_VERSION_STRING		std::string("2")
#define IMGF_MAJOR_BUILD_VERSION_CSTRING	"2"

#define IMGF_MINOR_BUILD_VERSION			9742
#define IMGF_MINOR_BUILD_VERSION_STRING		std::string("9742")
#define IMGF_MINOR_BUILD_VERSION_CSTRING	"9742"

#define IMGF_BUILD_VERSION_STRING			IMGF_MAJOR_BUILD_VERSION_STRING + string(".") + IMGF_MINOR_BUILD_VERSION_STRING