#pragma once

#include "nsbxcf.h"

using namespace bxcf;

enum bxcf::EExceptionCode // Note: When adding an enum entry here, also add the string equivalent in Format::getErrorReason.
{
	EXCEPTION_INVALID_DATA_SIZE_MULTIPLE,
	EXCEPTION_UNSUPPORTED_FORMAT_VERSION,
	EXCEPTION_UNKNOWN_ENCRYPTION_ALGORITHM_USED,
	EXCEPTION_UNSUPPORTED_GAME_USED,
	EXCEPTION_CANT_OPEN_FILE,
	EXCEPTION_FILE_READ_INSUFFICIENT_BYTES,
	EXCEPTION_CANT_SEEK_TO,
	EXCEPTION_FILE_PATH_NOT_SET,
	EXCEPTION_FILE_INVALID,
	EXCEPTION_CANT_RESTORE_PEEK,
	EXCEPTION_UNKNOWN_FORMAT,
	EXCEPTION_FILE_READ_FAIL,
	EXCEPTION_FILE_WRITE_FAIL,
	EXCEPTION_UNKNOWN_FORMAT_TYPE,
	EXCEPTION_UNSERIALIZE_INSUFFICIENT_DATA,
	EXCEPTION_INVALID_DATA_ORDER,
	EXCEPTION_UNKNOWN_DATA_STREAM_TYPE,
	EXCEPTION_UNKNOWN_ENTRY_TYPE
};